"""Build ``llms-full.txt`` from a fixed set of agent-facing source documents.

``llms-full.txt`` is the long-form companion to ``llms.txt``: concatenated
reference material in a single fetch for AI search engines (Perplexity,
Phind) and coding agents that prefer one document over chasing links. The
file is committed to the repo so external consumers can fetch it directly
from raw GitHub.

Run from anywhere::

    python scripts/build-llms-full.py

The public-surface contract test fails if any source document changed but
``llms-full.txt`` was not regenerated, so a PR that edits one of the
sources must also include the rebuilt ``llms-full.txt`` in the same commit.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "llms-full.txt"

SOURCES: tuple[str, ...] = (
    "AGENTS.md",
    "docs/agent-recipes.md",
    "docs/agent-contract-current.md",
    "docs/checks.md",
    "docs/concepts.md",
    "docs/autofix-policy.md",
)

_HEADER = """\
# Agents Shipgate · Long-Form Agent Reference (llms-full.txt)

> Single-fetch concatenation of the canonical agent-facing reference
> material. AI search engines and coding agents that prefer one document
> over chasing links should fetch this file. The short index is at
> [`llms.txt`](llms.txt); machine-readable triggers are at
> [`docs/triggers.json`](docs/triggers.json).
>
> Generated by `scripts/build-llms-full.py` from the source files below.
> Do not edit by hand — re-run the script to update.

## Sources (in order)

{sources}

---
"""


def render(repo_root: Path = REPO_ROOT) -> str:
    """Return the full ``llms-full.txt`` content as a string."""
    listing = "\n".join(f"- [`{src}`]({src})" for src in SOURCES)
    chunks: list[str] = [_HEADER.format(sources=listing)]
    for src in SOURCES:
        body = (repo_root / src).read_text(encoding="utf-8").rstrip()
        chunks.append(f"\n\n<!-- ===== source: {src} ===== -->\n\n{body}\n")
    return "".join(chunks)


def main() -> int:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(
        f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} "
        f"({OUTPUT_PATH.stat().st_size:,} bytes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
